---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  
provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[roundcube::default]
  - recipe[roundcube::nginx]
