---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  
provisioner:
  name: chef_solo

platforms:
- name: centos-6.6
  run_list: recipe[selinux::disabled]
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.8
  run_list: recipe[apt]
- name: fedora-20
  run_list: recipe[selinux::disabled]
- name: fedora-21
  run_list: recipe[selinux::disabled]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-14.10
  run_list: recipe[apt]

suites:
- name: default
  run_list:
  - recipe[roundcube_test]
