language: ruby
bundler_args: --without development integration
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
env:
  - CHEF_VERSION="~> 11.0"
  - CHEF_VERSION="~> 12.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: CHEF_VERSION="~> 12.0"
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec test/unit/spec
